<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN5efHSd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN5efHSd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN5efHSd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN5efHSd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN5efHSd\App_KernelDevDebugContainer([
    'container.build_hash' => 'N5efHSd',
    'container.build_id' => '14d7fa26',
    'container.build_time' => 1721629941,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN5efHSd');
