<?php

namespace ContainerX2AJn7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFoodControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FoodController' shared autowired service.
     *
     * @return \App\Controller\FoodController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FoodController.php';

        $container->services['App\\Controller\\FoodController'] = $instance = new \App\Controller\FoodController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\FoodRepository'] ?? $container->load('getFoodRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.QaaoWjx'] ?? $container->load('get_ServiceLocator_QaaoWjxService'))->withContext('App\\Controller\\FoodController', $container));

        return $instance;
    }
}
